// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/claim.go

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClaimServiceInterface is a mock of ClaimServiceInterface interface.
type MockClaimServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClaimServiceInterfaceMockRecorder
}

// MockClaimServiceInterfaceMockRecorder is the mock recorder for MockClaimServiceInterface.
type MockClaimServiceInterfaceMockRecorder struct {
	mock *MockClaimServiceInterface
}

// NewMockClaimServiceInterface creates a new mock instance.
func NewMockClaimServiceInterface(ctrl *gomock.Controller) *MockClaimServiceInterface {
	mock := &MockClaimServiceInterface{ctrl: ctrl}
	mock.recorder = &MockClaimServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimServiceInterface) EXPECT() *MockClaimServiceInterfaceMockRecorder {
	return m.recorder
}

// StoreClaim mocks base method.
func (m *MockClaimServiceInterface) StoreClaim(file *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreClaim", file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreClaim indicates an expected call of StoreClaim.
func (mr *MockClaimServiceInterfaceMockRecorder) StoreClaim(file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreClaim", reflect.TypeOf((*MockClaimServiceInterface)(nil).StoreClaim), file)
}

// MockClaimRepositoryInterface is a mock of ClaimRepositoryInterface interface.
type MockClaimRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClaimRepositoryInterfaceMockRecorder
}

// MockClaimRepositoryInterfaceMockRecorder is the mock recorder for MockClaimRepositoryInterface.
type MockClaimRepositoryInterfaceMockRecorder struct {
	mock *MockClaimRepositoryInterface
}

// NewMockClaimRepositoryInterface creates a new mock instance.
func NewMockClaimRepositoryInterface(ctrl *gomock.Controller) *MockClaimRepositoryInterface {
	mock := &MockClaimRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockClaimRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimRepositoryInterface) EXPECT() *MockClaimRepositoryInterfaceMockRecorder {
	return m.recorder
}

// SaveFile mocks base method.
func (m *MockClaimRepositoryInterface) SaveFile(file *multipart.FileHeader, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", file, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockClaimRepositoryInterfaceMockRecorder) SaveFile(file, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockClaimRepositoryInterface)(nil).SaveFile), file, filename)
}
