// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/identity.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/thiagogre/fabric-massified-insurances/test-network/rest-api-go/internal/domain"
)

// MockIdentityInterface is a mock of IdentityInterface interface.
type MockIdentityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityInterfaceMockRecorder
}

// MockIdentityInterfaceMockRecorder is the mock recorder for MockIdentityInterface.
type MockIdentityInterfaceMockRecorder struct {
	mock *MockIdentityInterface
}

// NewMockIdentityInterface creates a new mock instance.
func NewMockIdentityInterface(ctrl *gomock.Controller) *MockIdentityInterface {
	mock := &MockIdentityInterface{ctrl: ctrl}
	mock.recorder = &MockIdentityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityInterface) EXPECT() *MockIdentityInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityInterface) Create() (*domain.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(*domain.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityInterfaceMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityInterface)(nil).Create))
}
